### ISSUE TITLE
zone buff no longer works please help

### ISSUE THREAD

**Issue by ghost** [Cloticc/Eluna-scripts#2]
Unfortunately, the new AzerothCore version no longer works with zone buff 

https://github.com/Cloticc/Eluna-scripts/tree/master/Quality%20of%20life%20stuff/zone/sql%20version 

https://github.com/azerothcore/azerothcore-wotlk

the script prevents me from entering any commands in the game chat. If I delete sqlZoneBuffer v2.lua then everything works again. I would be pleased if you could fix it. Sorry I can't describe it better.

**Comment by Isidorsson** [comment]
Alright ill check it out.

**Comment by ghost** [comment]
Thank you very much, I think it's good that there are still people who repair or create Eluna scripts. Thank you for the great work.

**Comment by ghost** [comment]
question: can you also repair other lua scripts? I would also give something for that.

**Comment by Isidorsson** [comment]
> 

yes i could repair other script if need what's your discord id instead of talking here. or mine  Username: clotic#0
